# action.yml
name: 'Copy Git Meta'
description: 'A simple Action copying created by https://github.com/mavrck-inc/git-meta git meta and template files to S3'
inputs:
  version:
    description: 'The version of the service'
    required: true
  name:
    description: 'The name of the service'
    required: true
  bucket:
    description: 'The name of the bucket to put the files into'
    required: true
    default: mavrck-build-artifacts
  gitmeta:
    description: 'Git meta file path'
    required: true
    default: git-meta
  git_branch:
    description: 'Git branch for tagging'
    required: true
    default: branch
  gitmetaOutput:
    description: 'Git meta output file path'
    required: true
    default: gitMeta
  meta:
    description: 'Meta file path'
    required: true
    default: meta.yml
  metaOutput:
    description: 'Meta output file path'
    required: true
    default: meta.yml
  metrics:
    description: 'Metrics file path'
    required: true
    default: metrics.yml
  metricsOutput:
    description: 'Metrics output file path'
    required: true
    default: metrics.yml
  templateOutput:
    description: 'Template output'
    required: true
    default: cf.yml
  template:
    description: 'Template input file'
    required: true
    default: packaged.yaml
  terraform:
    description: 'Terraform zip file path'
    required: true
    default: terraform.zip
  terraformOutput:
    description: 'Terraform zip output file path'
    required: true
    default: terraform.zip

runs:
  using: 'node20'
  main: 'dist/index.js'
