name: "release"
on:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test and prepare distribution
      run: npm run all

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        extra_plugins: |
          @semantic-release/release-notes-generator
          @semantic-release/changelog
          @semantic-release/exec
          @semantic-release/github
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
