name: "release"
on:
  push:
    branches:
      - main

jobs:
  # unit tests
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test and prepare distribution
      run: npm install && npm run all

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        extra_plugins: |
          @semantic-release/release-notes-generator
          @semantic-release/changelog
          @semantic-release/exec
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
