name: "release"
on:
  push:
    branches:
      - *

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Test and prepare distribution
        run: npm install && npm run all

      - name: Git Status
        run: git status